version: '3.8'

services:
  db:
    image: mariadb:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
